/**
 * PKCE (RFC 7636) helpers for the Worker's OWN upstream leg - it is an OAuth
 * *client* to WordPress (this file), and separately an OAuth *server* to the
 * AI client (handled entirely by @cloudflare/workers-oauth-provider). Two
 * independent PKCE pairs exist in any single connection: one generated by
 * the AI client (verified by OAuthProvider), one generated here (verified
 * by Bridgistic\Oauth::redeem_code on the WordPress side). S256 only.
 */

function toBase64Url(bytes: Uint8Array): string {
  let binary = "";
  for (const b of bytes) binary += String.fromCharCode(b);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

export function generateCodeVerifier(): string {
  return toBase64Url(crypto.getRandomValues(new Uint8Array(32)));
}

export async function deriveCodeChallenge(verifier: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(verifier));
  return toBase64Url(new Uint8Array(digest));
}
